runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:6ZHQyRhyyCyGF8U2mnujTzqzGCKAxqg1hFfwOYLntmk
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
  DB_DATABASE: ecommerce
  DB_USERNAME: root
  DB_PASSWORD: Gnieg8VSIpzH
  DB_SOCKET: "/cloudsql/ecommerce-apatxee-v2:europe-west6:ecommerce-basic"

  MAIL_DRIVER: smtp
  MAIL_HOST: smtp.mailtrap.io
  MAIL_PORT: 2525
  MAIL_USERNAME: null
  MAIL_PASSWORD: null
  MAIL_ENCRYPTION: null

  JWT_SECRET: SEannlkXhUFJHWuVwvBHrj9SSs6zLqhPpNJGwaxt1EQR6OcsZgo9L5Qg4HGtUlKt
  PAACK_KEY: 88e316053355e5017c5df6372c310b287a4693e5
  ELINFORMAR_CLIENT_ID: 2ctnq8nqiobu91kpwl0hzwfl3b28x6iwf1f08fyp
  ELINFORMAR_CLIENT_SECRET: wl9e1mPswyEMA5txFTY6NlqDndLOzbCleUJux57FE1o
  TWILIO_SID: ACefd4718af2b07d2aa6936d3a37458cb0
  TWILIO_TOKEN: fb6e132e69e1152749032cdf5f5dc27a
  TWILIO_FROM: +34955160684
  TRUUST_PK:
  TRUUST_SK:
  STRIPE_KEY: pk_test_iOoJca2tObgjRwE7xbi0T3MM008BdX4xYU
  STRIPE_SECRET: sk_test_G9Qs20pym4a7Nr43SW3F3JDs00lEIQasj9
  STRIPE_WEBHOOK_SECRET:
  STRIPE_WEBHOOK_TOLERANCE:
  STRIPE_PLATFORM_ID: ca_F6nmQpdvp91cXjh0WFLXOJ6pav2MFSLx
