runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:6ZHQyRhyyCyGF8U2mnujTzqzGCKAxqg1hFfwOYLntmk
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
  DB_DATABASE: ecommerce
  DB_USERNAME: root
  DB_PASSWORD: Gnieg8VSIpzH
  DB_SOCKET: "/cloudsql/ecommerce-apatxee-v2:europe-west6:ecommerce-basic"

  MAIL_DRIVER: smtp
  MAIL_HOST: smtp.mailtrap.io
  MAIL_PORT: 2525
  MAIL_USERNAME: e026217f7741dc
  MAIL_PASSWORD: 77230e0f68397c
  MAIL_ENCRYPTION: null

  JWT_SECRET: SEannlkXhUFJHWuVwvBHrj9SSs6zLqhPpNJGwaxt1EQR6OcsZgo9L5Qg4HGtUlKt
  PAACK_KEY: 88e316053355e5017c5df6372c310b287a4693e5
  ELINFORMAR_CLIENT_ID: 2ctnq8nqiobu91kpwl0hzwfl3b28x6iwf1f08fyp.api.einforma.com
  ELINFORMAR_CLIENT_SECRET: wl9e1mPswyEMA5txFTY6NlqDndLOzbCleUJux57FE1o
  TWILIO_SID: ACa9d6b3a75f4aec74704d0af985727a55
  TWILIO_TOKEN: 340870f0aceb12a51cd90c0a489841ca
  TWILIO_FROM: +12407768185
  TRUUST_PK:
  TRUUST_SK:
  STRIPE_KEY: pk_test_iOoJca2tObgjRwE7xbi0T3MM008BdX4xYU
  STRIPE_SECRET: sk_test_G9Qs20pym4a7Nr43SW3F3JDs00lEIQasj9
  STRIPE_WEBHOOK_SECRET:
  STRIPE_WEBHOOK_TOLERANCE:
  STRIPE_PLATFORM_ID: ca_F6nmQpdvp91cXjh0WFLXOJ6pav2MFSLx

  FILESYSTEM_DRIVER: gcs
  GOOGLE_CLOUD_PROJECT_ID: ecommerce-apatxee-v2
  GOOGLE_CLOUD_STORAGE_BUCKET: ecommerce-apatxee-v2.appspot.com
  GOOGLE_CLOUD_KEY_FILE: ecommerce-apatxee-v2-2588124b1aab.json